restaurants = [
    {"name" : "La Pecora Bianca", "cuisine" : "italian", "pricing" : "$$", "location" : "nolita"},
    {"name" : "Gnoccheria by Luzzo's", "cuisine" : "italian", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "Cafeteria", "cuisine" : "american", "pricing" : "$$", "location" : "chelsea"},
    {"name" : "Dr Clark", "cuisine" : "japanese", "pricing" : "$$", "location" : "chinatown"},
    {"name" : "Golden Unicorn", "cuisine" : "chinese", "pricing" : "$", "location" : "chinatown"},
    {"name" : "Nom Wah Tea Parlor", "cuisine" : "chinese", "pricing" : "$", "location" : "chnatown"},
    {"name" : "Tasty Hand-Pulled Noodles", "cuisine" : "chinese", "pricing" : "$", "location" : "chinatown"},
    {"name" : "Xi'an Famous Foods", "cuisine" : "chinese", "pricing" : "$", "location" : "chinatown"},
    {"name" : "Rao's", "cuisine" : "italian", "pricing" : "$$$$", "location" : "east harlem"},
    {"name" : "Soothr", "cuisine" : "thai", "pricing" : "$$", "location" : "east village"},
    {"name" : "San Marzano", "cuisine" : "italian", "pricing" : "$", "location" : "east village"},
    {"name" : "Gemma", "cuisine" : "italian", "pricing" : "$$$", "location" : "east village"},
    {"name" : "Lucien", "cuisine" : "french", "pricing" : "$$$", "location" : "east village"},
    {"name" : "Supper", "cuisine" : "italian", "pricing" : "$$", "location" : "east village"},
    {"name" : "Thursday Kitchen", "cuisine" : "korean", "pricing" : "$$", "location" : "east village"},
    {"name" : "MOKYO", "cuisine" : "korean", "pricing" : "$$", "location" : "east village"},
    {"name" : "Temakase", "cuisine" : "japanese", "pricing" : "$$", "location" : "east village"},
    {"name" : "Lil Frankie's", "cuisine" : "italian", "pricing" : "$$", "location" : "east village"},
    {"name" : "Frank", "cuisine" : "italian", "pricing" : "$$", "location" : "east village"},
    {"name" : "Ippudo", "cuisine" : "japanese", "pricing" : "$$", "location" : "east village"},
    {"name" : "Jue Lan Club", "cuisine" : "chinese", "pricing" : "$$$", "location" : "flatiron"},
    {"name" : "Gramercy Tavern", "cuisine" : "vegan", "pricing" : "$$$$", "location" : "flatiron"},
    {"name" : "Scarpetta", "cuisine" : "italian", "pricing" : "$$$", "location" : "flatiron"},
    {"name" : "Sugarfish", "cuisine" : "japanese", "pricing" : "$$$", "location" : "flatiron"},
    {"name" : "KazuNori", "cuisine" : "japanese", "pricing" : "$$", "location" : "flatiron"},
    {"name" : "Cote", "cuisine" : "korean", "pricing" : "$$$", "location" : "flatiron"},
    {"name" : "Bar Pitti", "cuisine" : "italian", "pricing" : "$$$", "location" : "greenwich village"},
    {"name" : "DOMODOMO", "cuisine" : "japanese", "pricing" : "$$$", "location" : "greenwich village"},
    {"name" : "Raku", "cuisine" : "japanese", "pricing" : "$$", "location" : "greenwich village"},
    {"name" : "Carbone", "cuisine" : "italian", "pricing" : "$$$$", "location" : "greenwich village"},
    {"name" : "Charlie Bird", "cuisine" : "italian", "pricing" : "$$", "location" : "greenwich village"},
    {"name" : "Il Cantinori", "cuisine" : "italian", "pricing" : "$$$", "location" : "greenwich village"},
    {"name" : "Il Mulino", "cuisine" : "italian", "pricing" : "$$$$", "location" : "greenwich village"},
    {"name" : "Minetta Tavern", "cuisine" : "french", "pricing" : "$$$", "location" : "greenwich village"},
    {"name" : "Okinii", "cuisine" : "japanese", "pricing" : "$$$", "location" : "greenwich village"},
    {"name" : "Tomoe Sushi", "cuisine" : "japanese", "pricing" : "$$", "location" : "greenwich village"},
    {"name" : "Top Thai", "cuisine" : "thai", "pricing" : "$$", "location" : "greenwich village"},
    {"name" : "Barn Joo 35", "cuisine" : "korean", "pricing" : "$$", "location" : "koreatown"},
    {"name" : "Yoo Haeundae Galbi", "cuisine" : "korean", "pricing" : "$$$", "location" : "koreatown"},
    {"name" : "Il Cortile", "cuisine" : "italian", "pricing" : "$$", "location" : "little italy"},
    {"name" : "Aunt Jake's", "cuisine" : "italian", "pricing" : "$$", "location" : "little italy"},
    {"name" : "Dirty French", "cuisine" : "french", "pricing" : "$$$", "location" : "lower east side"},
    {"name" : "Forsythia", "cuisine" : "italian", "pricing" : "$$", "location" : "lower east side"},
    {"name" : "The Flower Shop", "cuisine" : "american", "pricing" : "$$", "location" : "lower east side"},
    {"name" : "Wayla", "cuisine" : "thai", "pricing" : "$$", "location" : "lower east side"},
    {"name" : "Catch NYC", "cuisine" : "seafood", "pricing" : "$$$", "location" : "meatpacking"},
    {"name" : "Pastis", "cuisine" : "french", "pricing" : "$$$", "location" : "meatpacking"},
    {"name" : "The Standard Grill", "cuisine" : "american", "pricing" : "$$$", "location" : "meatpacking"},
    {"name" : "STK Steakhouse", "cuisine" : "american", "pricing" : "$$$", "location" : "meatpacking"},
    {"name" : "Mean Fiddler", "cuisine" : "irish", "pricing" : "$$", "location" : "midtown"},
    {"name" : "Nobu", "cuisine" : "japanese", "pricing" : "$$$$", "location" : "midtown"},
    {"name" : "The Polo Bar", "cuisine" : "american", "pricing" : "$$$", "location" : "midtown"},
    {"name" : "Izakaya MEW", "cuisine" : "japanese", "pricing" : "$$", "location" : "midtown"},
    {"name" : "Totto Ramen", "cuisine" : "japanese", "pricing" : "$$", "location" : "midtown"},
    {"name" : "Quartino Bottega Organica", "cuisine" : "italian", "pricing" : "$$", "location" : "NoHo"},
    {"name" : "BondST", "cuisine" : "japanese", "pricing" : "$$$", "location" : "NoHo"},
    {"name" : "Fish Cheeks", "cuisine" : "thai", "pricing" : "$$$", "location" : "NoHo"},
    {"name" : "Il Buco Alimentari & Vineria", "cuisine" : "italian", "pricing" : "$$", "location" : "NoHo"},
    {"name" : "La Pecora Bianca", "cuisine" : "italian", "pricing" : "$$$", "location" : "Nolita"},
    {"name" : "Mister French", "cuisine" : "french", "pricing" : "$$$", "location" : "Nolita"},
    {"name" : "Pasquale Jones", "cuisine" : "italian", "pricing" : "$$$", "location" : "Nolita"},
    {"name" : "Peasant", "cuisine" : "italian", "pricing" : "$$$", "location" : "Nolita"},
    {"name" : "Rubirosa", "cuisine" : "italian", "pricing" : "$$", "location" : "Nolita"},
    {"name" : "Parm", "cuisine" : "italian", "pricing" : "$$", "location" : "Nolita"},
    {"name" : "Thai Diner", "cuisine" : "thai", "pricing" : "$$", "location" : "Nolita"},
    {"name" : "Balthazar", "cuisine" : "french", "pricing" : "$$$", "location" : "SoHo"},
    {"name" : "Lure Fishbar", "cuisine" : "seafood", "pricing" : "$$$", "location" : "SoHo"},
    {"name" : "Altro Paradiso", "cuisine" : "italian", "pricing" : "$$$", "location" : "SoHo"},
    {"name" : "Blue Ribbon Sushi", "cuisine" : "japanese", "pricing" : "$$", "location" : "SoHo"},
    {"name" : "Bubby's", "cuisine" : "american", "pricing" : "$$", "location" : "SoHo"},
    {"name" : "Cipriani Downtown", "cuisine" : "italian", "pricing" : "$$$$", "location" : "SoHo"},
    {"name" : "Mercer Kitchen", "cuisine" : "american", "pricing" : "$$$", "location" : "SoHo"},
    {"name" : "Raoul's Restaurant", "cuisine" : "french", "pricing" : "$$$", "location" : "SoHo"},
    {"name" : "The Dutch", "cuisine" : "american", "pricing" : "$$$", "location" : "SoHo"},
    {"name" : "Coco Pazzo", "cuisine" : "italian", "pricing" : "$$", "location" : "SoHo"},
    {"name" : "Galli", "cuisine" : "italian", "pricing" : "$$", "location" : "SoHo"},
    {"name" : "China Blue", "cuisine" : "chinese", "pricing" : "$$", "location" : "Tribeca"},
    {"name" : "Frenchette", "cuisine" : "french", "pricing" : "$$$$", "location" : "Tribeca"},
    {"name" : "Locande Verde", "cuisine" : "italian", "pricing" : "$$$", "location" : "Tribeca"},
    {"name" : "The Odeon", "cuisine" : "american", "pricing" : "$$$", "location" : "Tribeca"},
    {"name" : "Tribeca Grill", "cuisine" : "american", "pricing" : "$$$", "location" : "Tribeca"},
    {"name" : "Bar Italia", "cuisine" : "italian", "pricing" : "$$$", "location" : "Upper East Side"},
    {"name" : "Le Bilboquet", "cuisine" : "french", "pricing" : "$$$", "location" : "Upper East Side"},
    {"name" : "The Mark Restaurant", "cuisine" : "american", "pricing" : "$$$$", "location" : "Upper East Side"},
    {"name" : "THEP Thai Restaurant", "cuisine" : "thai", "pricing" : "$$", "location" : "Upper East Side"},
    {"name" : "UpThaai", "cuisine" : "thai", "pricing" : "$$", "location" : "Upper East Side"},
    {"name" : "American Bar", "cuisine" : "american", "pricing" : "$$$", "location" : "West Village"},
    {"name" : "Don Angie", "cuisine" : "italian", "pricing" : "$$$", "location" : "West Village"},
    {"name" : "Via Carota", "cuisine" : "italian", "pricing" : "$$$", "location" : "West Village"},
    {"name" : "L'Artusi", "cuisine" : "italian", "pricing" : "$$$", "location" : "West Village"},
    {"name" : "Emily", "cuisine" : "american", "pricing" : "$$", "location" : "West Village"},
    {"name" : "Palma", "cuisine" : "italian", "pricing" : "$$$", "location" : "West Village"},
    {"name" : "Corner Bistro", "cuisine" : "american", "pricing" : "$$", "location" : "West Village"},
    {"name" : "Hudson Clearwater", "cuisine" : "american", "pricing" : "$$$", "location" : "West Village"},
    {"name" : "Rosemary's", "cuisine" : "italian", "pricing" : "$$", "location" : "West Village"},
    {"name" : "Waverly Inn", "cuisine" : "american", "pricing" : "$$$", "location" : "West Village"},
    {"name" : "Sushi on Jones", "cuisine" : "japanese", "pricing" : "$$$", "location" : "West Village"},
    {"name" : "The Spaniard", "american" : "american", "pricing" : "$$", "location" : "West Village"},
    {"name" : "Boucherie", "cuisine" : "french", "pricing" : "$$$", "location" : "West Village"},
]