brunch = [
    {"name" : "PMF Pardon My French", "cuisine" : "french", "pricing" : "$$", "location" : "alphabet city"}, 
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"}, 
    {"name" : "Poco", "cuisine" : "spanish", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "The Kettle Black", "cuisine" : "american", "pricing" : "$$", "location" : "bay ridge"},
    {"name" : "Cookshop", "cuisine" : "american", "pricing" : "$$", "location" : "chelsea"},
    {"name" : "The Grey Dog", "cuisine" : "american", "pricing" : "$$", "location" : "chelsea"},
    {"name" : "Cornerstone Cafe", "cuisine" : "american", "pricing" : "$$", "location" : "east village"},
    {"name" : "San Marzano", "cuisine" : "italian", "pricing" : "$", "location" : "east village"},
    {"name" : "Jackdaw", "cuisine" : "irish", "pricing" : "$$", "location" : "east village"},
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"},
]