fast_food = [
    {"Name": "Tompkins Square Bagels", "Type": "bagels", "Price range": "$", "Location": "east village" },
    {"Name": "Brooklyn Bagel Co.", "Type": "bagels", "Price range": "$", "Location": "greenwich village" },
    {"Name": "Murray's Bagels", "Type": "bagels", "Price range": "$", "Location": "greenwich village" },
    {"Name": "Russ & Daughters", "Type": "bagels", "Price range": "$$", "Location": "lower east side },
    {"Name": "Ess-a-Bagel", "Type": "bagels", "Price range": "$", "Location": "midtown" },
    {"Name": "Smashed", "Type": "burgers", "Price range": "$", "Location": "lower east side" },
    {"Name": "Sticky's Finger Joint", "Type": "chicken fingers", "Price range": "$", "Location": "union square" },
    {"Name": "Katz's Delicatessen", "Type": "deli", "Price range": "$$", "Location": "lower east side" },
    {"Name": "Brooklyn Dumpling Shop", "Type": "dumplings", "Price range": "$$", "Location": "east village" },
    {"Name": "Go Go Curry", "Type": "japanese", "Price range": "$$", "Location": "greenwich village" },
    {"Name": "Oh K-Dog", "Type": "korean", "Price range": "$", "Location": "lower east side" },
    {"Name": "Murray's Mac & Cheese", "Type": "mac and cheese", "Price range": "$", "Location": "west village" },
    {"Name": "The Hummus & Pita Co.", "Type": "mediterranean", "Price range": "$", "Location": "chelsea" },
    {"Name": "Mamoun's Falafel", "Type": "middle eastern", "Price range": "$", "Location": "greenwich village" },
    {"Name": "Farook's Halal Food", "Type": "middle eastern", "Price range": "$", "Location": "union square" },
    {"Name": "East Village Pizza", "Type": "pizza", "Price range": "$", "Location": "east village" },
    {"Name": "Prince Street Pizza", "Type": "pizza", "Price range": "$", "Location": "nolita" },
    {"Name": "Unregular Pizza", "Type": "pizza", "Price range": "$", "Location": "union square" },
    {"Name": "Joe's Pizza", "Type": "pizza", "Price range": "$", "Location": "west village" },
    {"Name": "Bleecker Street Pizza", "Type": "pizza", "Price range": "$", "Location": "west village" },
    {"Name": "Cutlets Sandwich Co.", "Type": "sandwiches", "Price range": "$", "Location": "flatiron" },
    {"Name": "Panineria Italiana", "Type": "sandwiches", "Price range": "$$", "Location": "greenwich" },
    {"Name": "Melt Shop", "Type": "sandwiches", "Price range": "$", "Location": "theater district " }
]