brunch = [
    {"name" : "PMF Pardon My French", "cuisine" : "french", "pricing" : "$$", "location" : "alphabet city"}, 
    {"name" : "Lamia's Fish Market", "cuisine" : "seafood", "pricing" : "$$", "location" : "alphabet city"}, 
    {"name" : "Poco", "cuisine" : "spanish", "pricing" : "$$", "location" : "alphabet city"},
    {"name" : "Cookshop", "cuisine" : "american", "pricing" : "$$", "location" : "chelsea"},
    {"name" : "The Grey Dog", "cuisine" : "american", "pricing" : "$$", "location" : "chelsea"},
    {"name" : "Cornerstone Cafe", "cuisine" : "american", "pricing" : "$$", "location" : "east village"},
    {"name" : "San Marzano", "cuisine" : "italian", "pricing" : "$", "location" : "east village"},
    {"name" : "Jackdaw", "cuisine" : "irish", "pricing" : "$$", "location" : "east village"},
    {"name" : "Carroll Place", "cuisine" : "italian", "pricing" : "$$", "location" : "greenwich village"},
    {"name" : "Wicked Willy's", "cuisine" : "american", "pricing" : "$$", "location" : "greenwich village"},
    {"name" : "Jane", "cuisine" : "american", "pricing" : "$$", "location" : "greenwich village"},
    {"name" : "Egg Shop", "cuisine" : "american", "pricing" : "$$", "location" : "little italy"},
    {"name" : "La Mercerie", "cuisine" : "french", "pricing" : "$$", "location" : "lower east side"},
    {"name" : "Freemans", "cuisine" : "american", "pricing" : "$$", "location" : "lower east side"},
    {"name" : "Clinton Street Baking Company", "cuisine" : "american", "pricing" : "$$", "location" : "lower east side"},
    {"name" : "RH Rooftop Restaurant", "cuisine" : "american", "pricing" : "$$$", "location" : "meatpacking"},
    {"name" : "Mean Fiddler", "cuisine" : "irish", "pricing" : "$$", "location" : "midtown"},
    {"name" : "Sarabeth's", "cuisine" : "american", "pricing" : "$$", "location" : "midtown"},
    {"name" : "MUD", "cuisine" : "american", "pricing" : "$$", "location" : "east village"},
    {"name" : "Little Prince", "cuisine" : "french", "pricing" : "$$", "location" : "SoHo"},
    {"name" : "NOMO Kitchen", "cuisine" : "american", "pricing" : "$$", "location" : "SoHo"},
    {"name" : "Saint Ambroeus", "cuisine" : "italian", "pricing" : "$$$", "location" : "upper east side"},
    {"name" : "Buvette", "cuisine" : "french", "pricing" : "$$$", "location" : "west village"},
    {"name" : "Cafe Cluny", "cuisine" : "french", "pricing" : "$$", "location" : "west village"},
    {"name" : "Misi", "cuisine" : "italian", "pricing" : "$$$", "location" : "williamsburg"},
    {"name" : "Carthage Must be Destroyed", "cuisine" : "american", "pricing" : "$$$", "location" : "williamsburg"},
    {"name" : "Little Owl", "cuisine" : "american", "pricing" : "$$", "location" : "west village"},
]