desserts = [
    {"Name": "Sweet Moment", "Type": "desserts", "Price range": "$$", "Location": "chinatown" },
    {"Name": "Taiyaki NYC", "Type": "ice cream", "Price range": "$", "Location": "chinatown" },
    {"Name": "The Dough Club", "Type": "donuts", "Price range": "$", "Location": "chinatown" },
    {"Name": "46 Mott", "Type": "desserts", "Price range": "$", "Location": "chinatown" },
    {"Name": "Oddfellows Ice Cream Co.", "Type": "ice cream", "Price range": "$$", "Location": "dumbo" },
    {"Name": "Spot Dessert Bar", "Type": "desserts", "Price range": "$", "Location": "east village" },
    {"Name": "Morgenstern's Finest Ice Cream", "Type": "ice cream", "Price range": "$$", "Location": "greenwich village" },
    {"Name": "Surreal Creamery", "Type": "ice cream", "Price range": "$$", "Location": "greenwich village" },
    {"Name": "Posh Pop Bakeshop", "Type": "desserts", "Price range": "$$", "Location": "greenwich village" },
    {"Name": "Grace Street", "Type": "desserts", "Price range": "$$", "Location": "koreatown" },
    {"Name": "Keki Modern Cakes", "Type": "cakes", "Price range": "$$", "Location": "koreatown" },
    {"Name": "Milk & Cream Cereal Bar", "Type": "ice cream", "Price range": "$$", "Location": "little italy" },
    {"Name": "Soft Swerve", "Type": "ice cream", "Price range": "$", "Location": "lower east side" },
    {"Name": "Whipped - Urban Dessert Lab", "Type": "ice cream", "Price range": "$", "Location": "lower east side" },
    {"Name": "Doughnut Plant", "Type": "donuts", "Price range": "$$", "Location": "lower east side" },
    {"Name": "The Doughnuttery", "Type": "donuts", "Price range": "$$", "Location": "meatpacking" },
    {"Name": "Van Leeuwen Ice Cream", "Type": "ice cream", "Price range": "$$", "Location": "multiple locations" },
    {"Name": "Lady M", "Type": "cakes", "Price range": "$$", "Location": "multiple locations" },
    {"Name": "Little Cupcake Bakeshop", "Type": "cupcakes", "Price range": "$$", "Location": "nolita" },
    {"Name": "Ample Hills Creamery", "Type": "ice cream", "Price range": "$$", "Location": "prospect heights" },
    {"Name": "Sweet Rehab", "Type": "desserts", "Price range": "$$$", "Location": "soho" },
    {"Name": "Dominique Ansel Bakery", "Type": "desserts", "Price range": "$$", "Location": "soho" },
    {"Name": "mochidoki", "Type": "ice cream", "Price range": "$", "Location": "soho" },
    {"Name": "HARBS SoHo", "Type": "cakes", "Price range": "$$", "Location": "soho" },
    {"Name": "Levain Bakery", "Type": "cookies", "Price range": "$$", "Location": "upper west side" },
    {"Name": "Chip City", "Type": "cookies", "Price range": "$", "Location": "west village" },
    {"Name": "Magnolia Bakery", "Type": "desserts", "Price range": "$$", "Location": "west village" },
    {"Name": "Molly's Cupcakes", "Type": "cupcakes", "Price range": "$$", "Location": "west village" }
]