cafe = [
        {"Name": "Matto Expresso", "Type": "coffee shop", "Price range": "$", "Location": "east village"},
        {"Name": "Elsewhere Espresso", "Type": "coffee shop", "Price range": "$", "Location": "east village"},
        {"Name": "Prince Tea House", "Type": "tea house", "Price range": "$$", "Location": "east village"},
        {"Name": "Café Kitsune", "Type": "coffee shop", "Price range": "$$", "Location": "west village"},
        {"Name": "Café Select", "Type": "cafe", "Price range": "$$", "Location": "soho"},
        {"Name": "Juice Press", "Type": "juices", "Price range": "$$", "Location": "multiple locations"},
        {"Name": "Maman", "Type": "cafe", "Price range": "$$", "Location": "soho"},
        {"Name": "Think Coffee", "Type": "coffee shop", "Price range": "$", "Location": "multiple locations"},
        {"Name": "Saltwater Coffee", "Type": "coffee shop", "Price range": "$", "Location": "east village"},
        {"Name": "Irving Farm", "Type": "coffee shop", "Price range": "$", "Location": "multiple locations"},
        {"Name": "Le Fournil", "Type": "bakery", "Price range": "$$", "Location": "east village"},
        {"Name": "Fabrique", "Type": "bakery", "Price range": "$$", "Location": "meatpacking"},
        {"Name": "Debutea", "Type": "boba", "Price range": "$", "Location": "greenwich village"},
        {"Name": "Blue Bottle Coffee", "Type": "coffee shop", "Price range": "$$", "Location": "multiple locations"},
        {"Name": "Bluestone Lane", "Type": "cafe", "Price range": "$$", "Location": "multiple locations"},
        {"Name": "Chobani SoHo", "Type": "cafe", "Price range": "$$", "Location": "soho"} ,
        {"Name": "Bibble & Sip", "Type": "cafe", "Price range": "$", "Location": "little italy"},
        {"Name": "Devocion", "Type": "coffee shop", "Price range": "$", "Location": "flatiron"},
        {"Name": "Dr Smood", "Type": "coffee shop", "Price range": "$$", "Location": "soho"},
        {"Name": "Ground Support Coffee", "Type": "coffee shop", "Price range": "$", "Location": "soho"},
        {"Name": "Alimama", "Type": "coffee shop", "Price range": "$$", "Location": "chinatown"}
]